config/routes.rb
OneBody::Application.routes.draw do

  root to: redirect('/stream')

  resource :account do
    member do
      get :verify_code
      post :verify_code
      get  :select
      post :select
    end
  end

  resources :people do
    member do
      get :favs
      get :testimony
    end
    resources :friends do
      collection do
        post :reorder
      end
    end
    resources :relationships do
      collection do
        post :batch
      end
    end
    resource :account do
      member do
        get  :verify_code
        post :verify_code
        get  :select
        post :select
      end
    end
    resource :stream
    resource :photo
    resources :groups, :pictures, :services, :albums, :verses
    resource :privacy
  end

  resources :families do
    collection do
      post :batch
      post :select
    end
    resource :photo
    resources :relationships
    resources :people do
      member do
        post :update_position
      end
    end
    resource :search
  end

  resources :groups do
    collection do
      get  :batch
      post :batch
    end
    resources :memberships do
      collection do
        post   :batch
        delete :batch
      end
      resource :privacy
    end
    resources :messages do
      collection do
        post :new # XXX why??
      end
    end
    resources :attendance do
      collection do
        post :batch
      end
    end
    resources :tasks do
      member do
        patch :complete
        post :update_position
      end
    end
    resource :stream
    resource :photo
    resources :prayer_requests, :albums
    resource :calendar
  end

  resources :memberships do
    collection do
      get  :batch
      post :batch
    end
  end

  resources :service_categories do
    collection do
      get :batch_edit
      get :close_batch_edit
    end
  end

  resources :albums do
    resources :pictures do
      member do
        get :next
        get :prev
      end
      resource :photo
    end
  end

  resources :messages do
    resources :attachments
  end

  resource :emails

  resources :tags, only: :show

  resources :pictures, :prayer_signups, :authentications, :shares,
            :comments, :prayer_requests, :generated_files, :reports

  resources :verses do
    get 'search', on: :collection
  end

  resource :setup, :session, :search

  resources :printable_directories

  resource :stream do
    resources :people, controller: 'stream_people'
  end

  resources :news, as: :news_items
  get 'news', to: 'news#index'

  resources :attachments do
    member do
      get :get
    end
  end

  resources :pages, path: 'pages/admin' do
    resources :attachments
  end

  resources :documents do
    get :download, on: :member
  end

  resources :tasks do
    member do
      patch :complete
    end
  end

  resources :directory_maps do
    collection do
      get :family_locations
    end
  end

  get 'pages/*path' => 'pages#show_for_public', via: :get, as: :page_for_public

  get '/admin' => 'administration/dashboards#show'
  get '/admin/reports' => 'administration/reports#index'

  namespace :administration, path: :admin do
    resources :emails do
      collection do
        put :batch
      end
    end
    resources :settings do
      collection do
        put :batch
        put :reload
      end
    end
    resources :attendance do
      collection do
        get :prev
        get :next
      end
    end
    resources :deleted_people do
      collection do
        put :batch
      end
    end
    resources :imports do
      patch :execute, on: :member
    end
    resources :updates, :admins, :membership_requests
    namespace :checkin do
      root to: 'dashboards#show'
      resource :dashboard
      resources :groups do
        put :batch, on: :collection
        put :reorder, on: :member
      end
      resources :times do
        resources :groups
      end
      resources :cards, :auths, :labels
    end
    resources :custom_fields
    resources :custom_field_tabs
    resource :email_setup
  end

  resource :checkin, controller: 'checkin/checkins'
  namespace :checkin do
    resource :print
    resource :printer
    resources :families, :people, :groups
  end

  post '/pusher/auth_printer'    => 'pusher#auth_printer'
  get '/auth/facebook/callback'  => 'sessions#create_from_external_provider'
  post '/auth/facebook/callback' => 'sessions#create_from_external_provider'
  get '/auth/:provider/setup'    => 'sessions#setup_omniauth'
end

app/models/concerns/person/memberships.rb
require 'active_support/concern'

module Concerns
  module Person
    module Memberships
      extend ActiveSupport::Concern

      included do
        has_many :memberships, dependent: :destroy
        has_many :membership_requests, dependent: :destroy
        has_many :groups, through: :memberships
        after_destroy :destroy_memberships
      end

      def member_of?(group)
        memberships.where(group_id: group.id).any?
      end

      def destroy_memberships
        memberships.destroy_all
        membership_requests.destroy_all
      end
    end
  end
end

app/models/membership.rb
class Membership < ApplicationRecord
  include Authority::Abilities
  self.authorizer_name = 'MembershipAuthorizer'

  belongs_to :group
  belongs_to :person

  validates_uniqueness_of :group_id, scope: %i(site_id person_id)

  scope_by_site_id

  scope :order_by_birthday, -> { order('ifnull(month(people.birthday), 99)') }
  scope :order_by_name,     -> { order('people.first_name, people.last_name') }
  scope :leaders,           -> { where(leader: true) }

  def family
    person.family
  end

  serialize :roles, Array
  validate :validate_roles

  def validate_roles
    if roles.any? { |r| r !~ /\A[a-z0-9 \-_\(\)]+\z/i }
      errors.add(:roles, :invalid)
    end
  end

  before_create :generate_security_code

  def generate_security_code
    begin
      code = rand(999_999)
      write_attribute :code, code
    end until code > 0
  end

  def self.sharing_columns
    columns.map(&:name).select { |c| c =~ /^share_/ }
  end

  def only_admin?
    person && group &&
      group.admin?(person, :exclude_global_admins) &&
      group.admins.length == 1
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  skip_before_action :authenticate_user, only: %w(show update)
  before_action :authenticate_user_with_code_or_session, only: %w(show update)

  load_parent :group

  before_action :authorize_group_for_read,   only: :index
  before_action :authorize_group_for_update, only: :batch

  def show
    # allow email links to work (since they will be GET requests)
    if params[:email]
      render file: 'memberships/email'
    else
      raise ActionController::UnknownAction, t('No_action_to_show')
    end
  end

  def index
    @memberships = @group.memberships
                         .includes(:person)
                         .order(name_order)
                         .paginate(page: params[:page], per_page: 100)
    @memberships = if params[:birthdays]
                     @memberships.order_by_birthday
                   else
                     @memberships.order_by_name
                   end
    @requests = @group.membership_requests
  end

  # join group
  def create
    @person = Person.find(params[:id])
    if @logged_in.can_create?(@group.memberships.new)
      @group.memberships.create(person: @person)
    elsif me?
      @group.membership_requests.create(person: @person)
      flash[:warning] = t('groups.join.request_sent')
    end
    redirect_back(@group)
  end

  def update
    if params[:email]
      update_email
    elsif params[:promote] && @logged_in.can_update?(@group)
      update_admin
    elsif params[:leader] && @logged_in.can_update?(@group)
      update_leader
    else
      render html: t('not_authorized'), layout: true, status: 401
    end
  end

  def update_email
    @person = Person.find(params[:id])
    if can_update_email?
      @get_email = params[:email] == 'on'
      @group.set_options_for @person, get_email: @get_email
      respond_to do |format|
        format.html do
          render html: t('groups.email_settings_changed'), layout: true
        end
        format.js
      end
    else
      render html: t('not_authorized'), layout: true, status: 401
    end
  end

  def update_admin
    @membership = @group.memberships.find(params[:id])
    @membership.update_attribute(:admin, params[:promote] == 'true')
    render template: 'memberships/update_admin.js.erb'
  end

  def update_leader
    @membership = @group.memberships.find(params[:id])
    @membership.update_attribute(:leader, params[:leader] == 'true')
    render template: 'memberships/update_leader.js.erb'
  end

  # leave group
  def destroy
    @membership = @group.memberships.where(person_id: params[:id]).first!
    if @logged_in.can_delete?(@membership)
      if @membership.only_admin?
        flash[:warning] = t('groups.last_admin_remove', name: @membership.person.name)
      else
        @membership.destroy
      end
    end
    respond_to do |format|
      format.html { redirect_back(@group) }
      format.js
    end
  end

  def batch
    batch = MembershipBatch.new(@group, params[:ids])
    if request.post?
      batch.delete_requests
      @added = batch.create unless params[:commit] == 'ignore'
    elsif request.delete?
      batch.delete
    end
    @added ||= []
    respond_to do |format|
      format.js
      format.html { redirect_back(groups_path) }
    end
  end

  private

  def name_order
    if params[:order] == 'last'
      'people.last_name, people.first_name'
    else
      'people.first_name, people.last_name'
    end
  end

  def can_update_email?
    @logged_in.can_update?(@group) || @logged_in.can_update?(@person)
  end

  def authorize_group_for_read
    return if @logged_in.can_read?(@group)
    render html: t('not_authorized'), layout: true, status: :unauthorized
    false
  end

  def authorize_group_for_update
    return if @logged_in.can_update?(@group)
    render html: t('not_authorized'), layout: true, status: :unauthorized
    false
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
  def manually_added_person_in_linked_group_alert_icon(group, membership)
    return unless (group.linked? || group.parents_of?) && !membership.auto?
    icon(
      'fa fa-exclamation-circle text-gray',
      title: t('memberships.index.details.manual.tooltip')
    )
  end
end

app/views/memberships/_membership.haml
- person = membership.person
%tr.row-with-avatar{ id: "membership_#{membership.id}", style: defined?(hide) ? 'display:none' : '' }
  - if @logged_in.can_update?(@group)
    %td
      = check_box_tag 'ids[]', person.try(:id), false, class: 'checkbox simple'
  %td.avatar
    = avatar_tag person
  %td
    = link_to person do
      - if params[:order] == 'last'
        == #{person.last_name}, #{person.first_name}
      - else
        = person.name
    - if @logged_in.can_update?(@group)
      = manually_added_person_in_linked_group_alert_icon(@group, membership)
  - if params[:birthdays]
    %td
      = person.birthday.to_s(:date_without_year) if person.birthday
  - else
    %td
      = membership.created_at.to_s(:date) if membership.created_at
  - if @logged_in.can_update?(@group)
    %td
      = link_to group_membership_path(@group, membership, promote: false), data: { method: :put, remote: true }, id: "#{dom_id(membership)}_admin_demote", title: t('memberships.demote'), style: membership.admin? ? '' : 'display:none' do
        = icon 'fa fa-fw fa-check-square-o'
      = link_to group_membership_path(@group, membership, promote: true), data: { method: :put, remote: true }, id: "#{dom_id(membership)}_admin_promote", title: t('memberships.promote'), style: membership.admin? ? 'display:none' : '' do
        = icon 'fa fa-fw fa-square-o'
    %td
      = link_to group_membership_path(@group, membership, leader: false), data: { method: :put, remote: true }, id: "#{dom_id(membership)}_leader_false", title: t('memberships.leader_remove'), style: membership.leader? ? '' : 'display:none' do
        = icon 'fa fa-fw fa-check-square-o'
      = link_to group_membership_path(@group, membership, leader: true), data: { method: :put, remote: true }, id: "#{dom_id(membership)}_leader_true", title: t('memberships.leader_add'), style: membership.leader? ? 'display:none' : '' do
        = icon 'fa fa-fw fa-square-o'

app/views/memberships/batch.js.erb
if($('#memberships').length == 0) {
  location.reload();
} else {
  $('#memberships').prepend('<%= escape_javascript render(partial: 'membership', collection: @added, locals: { hide: true }) %>');
  $('<%= @added.map { |m| '#'+dom_id(m) }.join(',') %>').fadeIn(800);
  $('#add_person_name').val('')[0].focus();
  $('#add_people_form input[type="checkbox"]').attr('checked', false);
}

app/views/memberships/destroy.js.erb
$('#person<%= params[:id] %>').hide('slow', function(){$(this).detach()});
$('#people-heading').html('<%= escape_javascript t('people.person', count: @group.people.count) %>');

app/views/memberships/email.html.haml
= form_tag group_membership_path(@group, params[:id]), method: 'PATCH', id: 'email_form' do |form|
  = hidden_field_tag :email, params[:email]
  = hidden_field_tag :code, params[:code]

= content_for(:js) do
  :javascript
    $('#email_form').submit();

app/views/memberships/index.html.haml
- @title = t('.heading', group: link_to(@group.name, @group)).html_safe

.row

  .col-md-8
    - if @logged_in.can_update?(@group) and @requests.any?
      = form_tag batch_group_memberships_path(@group) do |form|
        .box.box-warning
          .box-header
            %h3.box-title= t('memberships.requests.heading')
          .box-body
            %table.table.print-full-width
              %tr
                %th
                %th
                %th= t('memberships.requests.name')
                %th= t('memberships.requests.created_at')
              - @requests.each do |req|
                %tr.row-with-avatar
                  %td
                    = check_box_tag 'ids[]', req.person.try(:id), false, class: 'checkbox'
                  %td.avatar
                    = avatar_tag req.person
                  %td
                    = link_to req.person.try(:name), req.person
                  %td
                    = req.created_at.to_s(:date)
          .box-footer
            .form-group
              = t('memberships.requests.select_some')
            .form-group
              = button_tag name: 'commit', value: 'accept', class: 'btn btn-success' do
                = icon 'fa fa-plus-circle'
                = t('memberships.requests.accept.button')
              = button_tag name: 'commit', value: 'ignore', class: 'btn btn-danger' do
                = icon 'fa fa-minus-circle'
                = t('memberships.requests.ignore.button')

    = pagination @memberships

    - if @group.people.any?
      = form_tag batch_group_memberships_path(@group), method: :delete do
        %table.members.table.print-full-width
          %thead
            %tr
              - if @logged_in.can_update?(@group)
                %th
              %th
              %th= link_to t('.details.name'), "?order=#{params[:order] == 'last' ? 'first' : 'last'}"
              - if params[:birthdays]
                %th= t('.details.birthday')
              - else
                %th= t('.details.created_at')
              - if @logged_in.can_update?(@group)
                %th= t('.details.admin')
                %th= t('.details.leader')
          %tbody#memberships
            - @memberships.includes(:person).order('people.last_name', 'people.first_name').each do |membership|
              - if person = membership.person
                = render partial: 'membership', object: membership

        - if @logged_in.can_update?(@group)
          .page-controls
            = button_tag class: 'btn btn-delete' do
              = icon 'fa fa-minus-circle'
              = t('.remove.button')

    - else
      %p= t('none')

    = pagination @memberships

  .col-md-4.hidden-print
    - if @logged_in.can_update?(@group)
      .box.box-success
        .box-header
          %h3.box-title
            = t('memberships.add.heading')
        .box-body
          - if @group.approved?
            = form_tag search_path, remote: true do
              = hidden_field_tag :select_person, true
              .form-group
                = label_tag :add_person_name do
                  = t('memberships.add.description')
                = text_field_tag 'name', nil, id: 'add_person_name', class: 'form-control', placeholder: t('memberships.add.name_placeholder')
                - if @group.parents_of?
                  .callout.callout-danger.push-down
                    = t('memberships.add.parents_of_warning_html', group: link_to(@group.parents_of_group.try(:name), @group.parents_of_group))
                - elsif @group.linked?
                  .callout.callout-danger.push-down
                    = t('memberships.add.linked_group_warning_html', code: @group.link_code)
              .form-group
                = button_tag t('search.search_by_name'), class: 'btn btn-info'
            #add_member{ style: 'display:none' }
              = form_tag batch_group_memberships_path(@group), remote: true, id: 'add_people_form' do
                = hidden_field_tag(:birthdays, true) if params[:birthdays]
                #results
                %p= button_tag t('search.add_selected'), class: 'btn btn-success'
          - else
            %p.very-strong
              = t('memberships.group_pending_approval')

app/views/memberships/update.js.erb
toggle = $('#group<%= @group.id %>');

<% if @get_email %>
  toggle.find('a.off').removeClass('toggle-disabled').addClass('toggle-enabled' );
  toggle.find('a.on' ).removeClass('toggle-enabled' ).addClass('toggle-disabled');
<% else %>
  toggle.find('a.on' ).removeClass('toggle-disabled').addClass('toggle-enabled' );
  toggle.find('a.off').removeClass('toggle-enabled' ).addClass('toggle-disabled');
<% end %>

app/views/memberships/update_admin.js.erb
$('<%= "##{dom_id(@membership)}_admin_promote" %>').toggle(<%= (!@membership.admin?).inspect %>)
$('<%= "##{dom_id(@membership)}_admin_demote" %>').toggle(<%= @membership.admin?.inspect %>)

app/views/memberships/update_leader.js.erb
$('<%= "##{dom_id(@membership)}_leader_true" %>').toggle(<%= (!@membership.leader?).inspect %>)
$('<%= "##{dom_id(@membership)}_leader_false" %>').toggle(<%= @membership.leader?.inspect %>)