config/routes.rb
OneBody::Application.routes.draw do

  root to: redirect('/stream')

  resource :account do
    member do
      get :verify_code
      post :verify_code
      get  :select
      post :select
    end
  end

  resources :people do
    member do
      get :favs
      get :testimony
    end
    resources :friends do
      collection do
        post :reorder
      end
    end
    resources :relationships do
      collection do
        post :batch
      end
    end
    resource :account do
      member do
        get  :verify_code
        post :verify_code
        get  :select
        post :select
      end
    end
    resource :stream
    resource :photo
    resources :groups, :pictures, :services, :albums, :verses
    resource :privacy
  end

  resources :families do
    collection do
      post :batch
      post :select
    end
    resource :photo
    resources :relationships
    resources :people do
      member do
        post :update_position
      end
    end
    resource :search
  end

  resources :groups do
    collection do
      get  :batch
      post :batch
    end
    resources :memberships do
      collection do
        post   :batch
        delete :batch
      end
      resource :privacy
    end
    resources :messages do
      collection do
        post :new # XXX why??
      end
    end
    resources :attendance do
      collection do
        post :batch
      end
    end
    resources :tasks do
      member do
        patch :complete
        post :update_position
      end
    end
    resource :stream
    resource :photo
    resources :prayer_requests, :albums
    resource :calendar
  end

  resources :memberships do
    collection do
      get  :batch
      post :batch
    end
  end

  resources :service_categories do
    collection do
      get :batch_edit
      get :close_batch_edit
    end
  end

  resources :albums do
    resources :pictures do
      member do
        get :next
        get :prev
      end
      resource :photo
    end
  end

  resources :messages do
    resources :attachments
  end

  resource :emails

  resources :tags, only: :show

  resources :pictures, :prayer_signups, :authentications, :shares,
            :comments, :prayer_requests, :generated_files, :reports

  resources :verses do
    get 'search', on: :collection
  end

  resource :setup, :session, :search

  resources :printable_directories

  resource :stream do
    resources :people, controller: 'stream_people'
  end

  resources :news, as: :news_items
  get 'news', to: 'news#index'

  resources :attachments do
    member do
      get :get
    end
  end

  resources :pages, path: 'pages/admin' do
    resources :attachments
  end

  resources :documents do
    get :download, on: :member
  end

  resources :tasks do
    member do
      patch :complete
    end
  end

  resources :directory_maps do
    collection do
      get :family_locations
    end
  end

  get 'pages/*path' => 'pages#show_for_public', via: :get, as: :page_for_public

  get '/admin' => 'administration/dashboards#show'
  get '/admin/reports' => 'administration/reports#index'

  namespace :administration, path: :admin do
    resources :emails do
      collection do
        put :batch
      end
    end
    resources :settings do
      collection do
        put :batch
        put :reload
      end
    end
    resources :attendance do
      collection do
        get :prev
        get :next
      end
    end
    resources :deleted_people do
      collection do
        put :batch
      end
    end
    resources :imports do
      patch :execute, on: :member
    end
    resources :updates, :admins, :membership_requests
    namespace :checkin do
      root to: 'dashboards#show'
      resource :dashboard
      resources :groups do
        put :batch, on: :collection
        put :reorder, on: :member
      end
      resources :times do
        resources :groups
      end
      resources :cards, :auths, :labels
    end
    resources :custom_fields
    resources :custom_field_tabs
    resource :email_setup
  end

  resource :checkin, controller: 'checkin/checkins'
  namespace :checkin do
    resource :print
    resource :printer
    resources :families, :people, :groups
  end

  post '/pusher/auth_printer'    => 'pusher#auth_printer'
  get '/auth/facebook/callback'  => 'sessions#create_from_external_provider'
  post '/auth/facebook/callback' => 'sessions#create_from_external_provider'
  get '/auth/:provider/setup'    => 'sessions#setup_omniauth'
end

app/controllers/administration/reports_controller.rb
class Administration::ReportsController < ApplicationController
  def index
    @reports = I18n.t('reports.reports')
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  REPORTS = {
    'attendance_totals'     => AttendanceTotalsReport,
    'group_contact_details' => GroupContactDetailsReport,
    'weekly_attendance'     => WeeklyAttendanceReport
  }.freeze

  def show
    report_class = REPORTS[params[:id]]
    raise ActiveRecord::RecordNotFound unless report_class
    @report = report_class.new(params.to_unsafe_h[:options] || {})
    respond_to do |format|
      format.html do
        render file: Rails.root.join('app/views/reports', params[:id] + '.html.haml')
      end
      format.csv do
        send_data @report.to_csv, filename: params[:id] + '.csv', type: 'text/csv'
      end
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def format_dateparam(date_in, *date_if_blank)
    date_if_blank = Date.current if date_if_blank.empty?
    Date.parse_in_locale(date_in.to_s) || Date.parse_in_locale(date_if_blank.to_s)
  end

  def format_date(value)
    value.to_s(:date) if value.is_a?(Time)
  end

  def report_date_field(form, name, _value)
    content_tag(:div, class: 'input-group') do
      content_tag(:div, class: 'input-group-btn') do
        content_tag(:button, type: 'button', class: 'btn btn-info date-picker-btn') do
          icon('fa fa-calendar')
        end
      end +
        form.date_field(name, class: 'form-control')
    end
  end

  def initialize_group
    @group = Group.find(options[:group_id]) if options[:group_id].present?
  end

  def group_title(report_title)
    I18n.t(
      @group ? 'title_for_group' : 'title',
      scope: report_title,
      group: @group.try(:name)
    )
  end

  def report_group_field(form, name)
    form.collection_select name, Group.approved.order(:name), :id, :name, { prompt: t('reports.group_select') }, class: 'form-control'
  end
end

app/views/reports/_body.html.haml
%tbody
  - @report.results.each do |row|
    %tr
      - row.each do |value|
        %td
          - if value.respond_to?(:strftime)
            = value.to_s(:full)
          - else
            = value

app/views/reports/_count.html.haml
.row
  .col-md-9
    = t('reports.records', count: @report.results.size)

app/views/reports/_submit.html.haml
= link_to report_path(@report, options: params[:options].to_unsafe_h, format: 'csv'), class: 'btn btn-info' do
  = icon 'fa fa-download'
  CSV

app/views/reports/_title.html.haml
- content_for :header do
  %section.content-header
    = breadcrumbs
    %h1
      = @report.formatted_title

app/views/reports/attendance_totals.html.haml
= render partial: 'title'
.row
  .col-md-9
    %table.table
      %thead
        %tr
          - @report.headings.each do |heading|
            %th= heading
      = render partial: 'body'
  .col-md-3
    .box.box-info.hidden-print
      .box-heading
      .box-body
        = form_for @report, as: :options, url: url_for, html: {method: :get} do |f|
          .form-group
            = f.label :fromdate, t('reports.from_date')
            = report_date_field f, :from_date, @report.from_date
          .form-group
            = f.label :thrudate, t('reports.thru_date')
            = report_date_field f, :thru_date, @report.thru_date
          .form-group
            = f.submit t('reports.submit'), class: 'btn btn-info'
            = render partial: 'submit'

= render partial: 'count'

app/views/reports/group_contact_details.html.haml
= render partial: 'title'
.row
  .col-md-9
    %table.table
      %thead
        %tr
          - @report.headings.each do |heading|
            %th= heading
      = render partial: 'body'
  .col-md-3
    .box.box-info.hidden-print
      .box-heading
      .box-body
        = form_for @report, as: :options, url: url_for, html: {method: :get} do |f|
          .form-group
            = f.label t('reports.group')
            = report_group_field f, :group_id
          .form-group
            = f.submit t('reports.submit'), class: 'btn btn-info'
            = render partial: 'submit'

= render partial: 'count'

app/views/reports/weekly_attendance.html.haml
= render partial: 'title'
.row
  .col-md-9
    %table.table
      %thead
        %tr
          - @report.headings.each do |heading|
            %th= heading
          = render partial: 'body'
  .col-md-3
    .box.box-info.hidden-print
      .box-heading
      .box-body
        = form_for @report, as: :options, url: url_for, html: {method: :get} do |f|
          .form-group
            = f.label :from_date, t('reports.from_date')
            = report_date_field f, :from_date, @report.from_date
          .form-group
            = f.label :thru_date, t('reports.thru_date')
            = report_date_field f, :thru_date, @report.thru_date
          .form-group
            = f.label t('reports.group')
            = f.collection_select :group_id, Group.approved.order(:name), :id, :name, { prompt: t('reports.group_select') }, { class: 'form-control' }
          .form-group
            = f.submit t('reports.submit'), class: 'btn btn-info'
            = render partial: 'submit'

= render partial: 'count'